#!/bin/bash
# Copyright (c) 2024 by the Flatcar Maintainers.
# Use of this source code is governed by the Apache 2.0 license.

# Mangler script for the development sysext.
# Called by build_image -> dev_container_util.sh -> build_sysext.
#
# Mandatory positional arguments
# 1. image_root  - root directory of the image (sysext + rootfs).
#                  Passed by build_sysext.
# 2. binhost_url - complete URL for binpackages.
#                  Passed via --manglefs_script_args. 

image_root="${1}"
binhost_url="${2}"

devext_basedir="/usr/share/flatcar/devext"

# We're in build_library/, script root is one up
SCRIPT_ROOT="$(cd "$(dirname "$(readlink -f "$0")")/../"; pwd)"
. "${SCRIPT_ROOT}/common.sh" || exit 1

# Script must run inside the chroot
assert_inside_chroot
switch_to_strict_mode


# run_ldconfig, run_localedef
source "${BUILD_LIBRARY_DIR}/build_image_util.sh" || exit 1
# get_board_*
source "${BUILD_LIBRARY_DIR}/toolchain_util.sh" || exit 1

pushd "${image_root}"

info "devext: running ldconfig, localedef."
ARCH=$(get_board_arch $BOARD)
CHOST=$(get_board_chost $BOARD)
export ARCH CHOST

run_ldconfig .
run_localedef .

info "devext: capturing portage state."
mkdir -p .${devext_basedir}/var/db \
         .${devext_basedir}/var/lib/portage \
         .${devext_basedir}/etc/portage/repos.conf

cp -R --dereference ./var/db/pkg .${devext_basedir}/var/db/


for src in portage-stable coreos-overlay; do
    mkdir -p ".${devext_basedir}/var/lib/portage/${src}"
    cp -R --dereference \
            "${SRC_ROOT}/third_party/${src}/metadata" \
            "${SRC_ROOT}/third_party/${src}/profiles" \
            ".${devext_basedir}/var/lib/portage/${src}"
done

info "devext: generating portage config"

cat >".${devext_basedir}/etc/portage/repos.conf/portage-stable.conf" <<EOF
[DEFAULT]
main-repo = portage-stable
EOF

for src in portage-stable coreos-overlay; do
    cat  >>".${devext_basedir}/etc/portage/repos.conf/${src}.conf" <<EOF
[${src}]
location = /var/lib/portage/${src}
EOF

done

cat >".${devext_basedir}/etc/portage/make.conf" <<EOF
# make.conf for Flatcar development sysext
ARCH=${ARCH}
CHOST=${CHOST}

# on-instance /var/lib/portage is an overlayfs backed by ${devext_basedir}/var
DISTDIR="/var/lib/portage/distfiles"
PKGDIR="/var/lib/portage/pkgs"
PORT_LOGDIR="/var/log/portage"
PORTAGE_BINHOST="${binhost_url}"
EOF

profile=$(get_board_profile "${BOARD}")
profile="${profile#*:}/dev"

ln -s "${devext_basedir}/var/lib/portage/coreos-overlay/profiles/${profile}" \
        .${devext_basedir}/etc/portage/make.profile

popd
