name: "PR command build dispatcher"
on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-pr-command-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  check_maintainer_membership:
    # Only run if this is a PR comment that contains a valid command
    if: |
      ${{ github.event.issue.pull_request }} &&
        (    contains(github.event.comment.body, '/update-sdk')
          || contains(github.event.comment.body, '/build-image') )
    name: Check if commenter is in the Flatcar maintainers team
    outputs:
      maintainers: steps.step1.output.maintainers
    runs-on:
      - ubuntu-latest
    steps:
      - name: Fetch members of the maintainers team
        env:
          requester: ${{ github.event.comment.user.login }}
        shell: bash
        run: |
          curl -L --silent \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: Bearer ${{ secrets.GH_ACTIONS_ORG_READ }}" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  https://api.github.com/orgs/flatcar/teams/flatcar-maintainers/members \
              | jq -r '.[].login' > maintainers.txt

          echo "Current members of the maintainers team:"
          cat maintainers.txt

          res=false
          echo "Checking for membership of '${{ env.requester }}'"
          if grep -qE "^${{ env.requester }}$" maintainers.txt ; then
            echo "Succeeded."
            res=true
          else
            echo "FAILED: '${{ env.requester }} is not a member of the Flatcar maintainers team."
          fi

          $res

  update_sdk:
    needs: check_maintainer_membership
    if: ( always() && needs.check_maintainer_membership.result == 'success'
                   && contains(github.event.comment.body, '/update-sdk') )
    name: "Build an updated SDK container"
    # SDK build needs access to bincache ssh secret
    secrets: inherit
    uses: ./.github/workflows/update-sdk.yaml

  build_image:
    needs: [ check_maintainer_membership, build_sdk ]
    if: ( always() && needs.check_maintainer_membership.result == 'success'
                   && (    contains(github.event.comment.body, '/build-image')
                        || needs.build_sdk.result == 'success' ) )
    name: "Build the OS image"
    uses: ./.github/workflows/ci.yaml
    with:
      custom_sdk_version: ${{ needs.update_sdk.outputs.sdk_version }}
      image_formats: qemu_uefi
